baseURL: http://innolost.github.io
languageCode: en-us
title: innolost
paginate: 5
theme: PaperMod

minify:
  disableXML: true
  minifyOutput: true

params:
  env: dev # to enable google analytics, opengraph, twitter-cards and schema.
  title: innolost
  description: "innolost's personel site"
  keywords: [Blog, Portfolio]
  disableSpecial1stPost: true
  hideSummary: true